after_success: ./gradlew sonarqube

branches:
    only:
        - master

dist: trusty

jdk:
    - openjdk8
    - openjdk9
    - openjdk10
    - openjdk11
    - openjdk-ea
    - oraclejdk8

language: java

script: ./gradlew jacocoTestReport

sudo: false
